### PR TITLE
Fix Google Play Billing library, now 5.2.1 for compatibility with Android 14

### PR DESCRIPTION
**Pull request by finepointcgi**
Moved to 5.2 not 5.4
Addresses #51 for some reason i fat fingered the 2 into a 4

### CODE REVIEW

**Comment by finepointcgi** [comment]
> @finepointcgi
> 
> Thx!
> 
> Could you publish a release for this somewhere, people keep asking for a Billing Plugin that works with Godot 4, would be nice to be able to point them to a release they can just drop to their projects.

I have a release out here

https://github.com/finepointcgi/godot-google-play-billing/releases/tag/1.1.2

**Comment by NianoTT** [comment]
> > @finepointcgi
> > Thx!
> > Could you publish a release for this somewhere, people keep asking for a Billing Plugin that works with Godot 4, would be nice to be able to point them to a release they can just drop to their projects.
> 
> I have a release out here
> 
> https://github.com/finepointcgi/godot-google-play-billing/releases/tag/1.1.2

Thank you! :)

**Comment by NianoTT** [comment]
@finepointcgi might be worth changing it to 5.2.1 directly instead? 

5.2.1 (or 6) is required to target Android 14, and from the release notes there seems to be no functional difference on the user side for 5.2.1 compared to 5.2

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
